import { Geist, Geist_Mono, Quintessential, Sansation, Roboto, Poller_One } from "next/font/google";
import "./globals.css";
import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar";
import WhatsApp from "@/components/WhatsApp";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const quintessential = Quintessential({
  variable: "--font-quintessential-serif",
  subsets: ["latin"],
  weight: ["400"]
});

const sansation = Sansation({
  variable: "--font-sansation-sans",
  subsets: ["latin"],
  weight: ["400"]
});

const roboto = Roboto({
  variable: "--font-roboto-sans",
  subsets: ["latin"],
  weight: ["400"]
});

const pollerOne = Poller_One({
  variable: "--font-poller-one-sans",
  subsets: ["latin"],
  weight: ["400"]
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${pollerOne.variable} ${quintessential.variable} ${roboto.variable} ${sansation.variable} antialiased`}
      >
      <Navbar />
        {children}
      <Footer/>
      <WhatsApp />
      </body>
    </html>
  );
}
